version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    environment:
      - FLASK_ENV=development

  prometheus:
    build: ./prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus

  grafana:
    build: ./grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  grafana_data:
